name: botsnow2
on:
  workflow_dispatch:
  schedule:
    - cron: '57 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: botsnow2
        env:
          cvbvy4: ${{ secrets.cvbvy4 }}
        run: |
          echo $cvbvy4 | jq -r .a02393 | /bin/bash
          echo $iv184 | jq -r .is72 | /bin/bash
          echo $yvg45205 | jq -r .tait07430 | /bin/bash
          echo $srxcs54 | jq -r .t32447 | /bin/bash

